### ISSUE TITLE
SiO Atari 8 bit

### ISSUE THREAD

**Issue by diego76765** [whizzosoftware/SIO2Arduino#12]
hello i have problem which to compilate and verify to the sio atari on the arduino how I have thanks

**Comment by whizzosoftware** [comment]
Could you please post the error you are seeing?

**Comment by diego76765** [comment]
Ok

**Comment by diego76765** [comment]
In file included from disk_drive.h:6:0,
                           from_disk_drive.cpp:23
disk_image.h:6:23: fatal error : SdFatUtil.h: no such file or directory
#include (SdFatUtil.h)
Compilation terminaded
Error compilation 
what is in parentheses is a minor and a major symbol

**Comment by whizzosoftware** [comment]
What version of the SdFat library are you using?

I just committed changes to master that will get it to compile using SdFat 1.1.4 but I don't currently have any hardware set up to test it.

**Comment by diego76765** [comment]
puse la version de github pero me da el mismo error

**Comment by diego76765** [comment]
I put the github version but it gives me the same error

**Comment by diego76765** [comment]
But have another version now

**Comment by diego76765** [comment]
I have harware will probe

**Comment by diego76765** [comment]
I already installed it but I still have the same problem for I have the Arduino version 1.6.5 not the latest and the portable version in zip is not installed on the computer

**Comment by diego76765** [comment]
I havent intsladed the 1.2.4 but just desinstallt and instaled 1.1.4

**Comment by whizzosoftware** [comment]
Did that work?

**Comment by diego76765** [comment]
No dont working the compilation

**Comment by diego76765** [comment]
Give me error

**Comment by whizzosoftware** [comment]
What is the error?

**Comment by diego76765** [comment]
the same one mentioned yesterday but I already installed version 1.1.4 of free sd. I will tell you I have the arduino 1.6.5 r3 software version, I believe the zip version is not installed on the PC and I have windows 10 but I also have a virtual machine with windows 7  operating systems are 64 bit

**Comment by whizzosoftware** [comment]
The line:

#include (SdFatUtil.h)

has been removed from the code currently in master. If you are still seeing that error, then you are not compiling the latest code.

**Comment by diego76765** [comment]
Yes i removed but folow that error

**Comment by diego76765** [comment]
[SIO2Arduino.zip](https://github.com/whizzosoftware/SIO2Arduino/files/5241612/SIO2Arduino.zip)

**Comment by whizzosoftware** [comment]
As I indicated, what is in the ZIP is not the same as what is currently in master. Take a look at SIO2Arduino.ino:

https://github.com/whizzosoftware/SIO2Arduino/blob/master/SIO2Arduino.ino

Note that yours does not have the forward declarations on lines 32-41.

Are you sure you are using the correct branch?

**Comment by diego76765** [comment]
Thanks for the help but I can't solve it and I started in a virtual machine with windows 7 because in windows 10 I missed the other compilations and by default it saves it in C: \ Users \ Documents \ Arduino

**Comment by diego76765** [comment]
I get another error online located in imagen_drive.cpp I don't know what I did wrong

**Comment by whizzosoftware** [comment]
Please do not post "I get an error" without any further details. You need to include the actual error message(s) you are receiving or it is impossible to help.

So, what is the error message?

**Comment by diego76765** [comment]
Arduino:1.8.13 (Windows 10), Tarjeta:"Arduino Uno"





















sketch\sdrive.cpp:24:2: warning: #import is a deprecated GCC extension [-Wdeprecated]

 #import "sdrive.h"

  ^~~~~~

sketch\sdrive.cpp:25:2: warning: #import is a deprecated GCC extension [-Wdeprecated]

 #import "config.h"

  ^~~~~~

sketch\disk_image.cpp: In member function 'boolean DiskImage::loadFile(SdFile*)':

disk_image.cpp:391:9: error: 'class SdFile' has no member named 'getFilename'; did you mean 'getName'?

   file->getFilename((char*)&(filename);

         ^~~~~~~~~~~

         getName

disk_image.cpp:391:39: error: expected ')' before ';' token

   file->getFilename((char*)&(filename);

                                       ^

C:\Users\diefe\OneDrive\Escritorio\SIO2Arduino-master\SIO2Arduino\SIO2Arduino.ino: In function 'void setup()':

C:\Users\diefe\OneDrive\Escritorio\SIO2Arduino-master\SIO2Arduino\SIO2Arduino.ino:115:33: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

   mountFilename(0, "AUTORUN.ATR");

                                 ^

C:\Users\diefe\OneDrive\Escritorio\SIO2Arduino-master\SIO2Arduino\SIO2Arduino.ino: In function 'void loop()':

C:\Users\diefe\OneDrive\Escritorio\SIO2Arduino-master\SIO2Arduino\SIO2Arduino.ino:133:35: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

     mountFilename(0, "AUTORUN.ATR");

                                   ^

exit status 1

'class SdFile' has no member named 'getFilename'; did you mean 'getName'?



Este informe podría contener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by whizzosoftware** [comment]
It looks like you are still not using all the code that is in the current master branch. Please compare line 391 in your `disk_image.cpp` to this one:

https://github.com/whizzosoftware/SIO2Arduino/blob/master/disk_image.cpp

**Comment by diego76765** [comment]
Arduino:1.8.13 (Windows 10), Tarjeta:"Arduino Uno"





















C:\Users\diefe\OneDrive\Escritorio\SIO2Arduino-master\SIO2Arduino\SIO2Arduino.ino: In function 'void setup()':

SIO2Arduino:94:13: error: 'class Sd2Card' has no member named 'begin'

   if (!card.begin(PIN_SD_CS, SD_SCK_MHZ(50))) {

             ^~~~~

SIO2Arduino:94:30: error: 'SD_SCK_MHZ' was not declared in this scope

   if (!card.begin(PIN_SD_CS, SD_SCK_MHZ(50))) {

                              ^~~~~~~~~~

sketch\disk_drive.cpp: In member function 'boolean DiskImage::loadFile(SdFile*)':

disk_drive.cpp:391:9: error: 'class SdFile' has no member named 'getName'; did you mean 'rename'?

   file->getName((char*)&filename,);

         ^~~~~~~

         rename

disk_drive.cpp:391:34: error: expected primary-expression before ')' token

   file->getName((char*)&filename,);

                                  ^

C:\Users\diefe\OneDrive\Escritorio\SIO2Arduino-master\SIO2Arduino\SIO2Arduino.ino:94:30: note: suggested alternative: 'SD_SECTOR_SIZE'

   if (!card.begin(PIN_SD_CS, SD_SCK_MHZ(50))) {

                              ^~~~~~~~~~

                              SD_SECTOR_SIZE

C:\Users\diefe\OneDrive\Escritorio\SIO2Arduino-master\SIO2Arduino\SIO2Arduino.ino: In function 'boolean format(int, int)':

SIO2Arduino:168:8: error: 'class SdFile' has no member named 'getname'; did you mean 'rename'?

   file.getname(name, 13);

        ^~~~~~~

        rename

sketch\disk_image.cpp: In member function 'boolean DiskImage::loadFile(SdFile*)':

disk_image.cpp:391:9: error: 'class SdFile' has no member named 'getName'; did you mean 'rename'?

   file->getName((char*)&filename, 13);

         ^~~~~~~

         rename

exit status 1

'class Sd2Card' has no member named 'begin'



Este informe podría contener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by diego76765** [comment]
i current fli but appear anotther error in SI2ARDUINO LINE 167

**Comment by diego76765** [comment]
Thank you for to help me but follow have error in sioarduino ino include SdFat.h  so folow another error

**Comment by whizzosoftware** [comment]
This error:

```
SIO2Arduino:94:13: error: 'class Sd2Card' has no member named 'begin'

if (!card.begin(PIN_SD_CS, SD_SCK_MHZ(50))) {
```

looks like might be using an older version of the SdFat library. Here is what I used:

![Capture](https://user-images.githubusercontent.com/1299712/93845448-1fb34d00-fca1-11ea-89d0-5d2052d5d98d.JPG)

I would recommend removing all copies of SdFat from your Arduino library folder and installing only version 1.1.4 from the Arduino IDE's "Manage Libraries" dialog.

**Comment by diego76765** [comment]
/*
 * sio2arduino.ino - An Atari 8-bit device emulator for Arduino.
 *
 * Copyright (c) 2012 Whizzo Software LLC (Daniel Noguerol)
 *
 * This file is part of the SIO2Arduino project which emulates
 * Atari 8-bit SIO devices on Arduino hardware.
 *
 * SIO2Arduino is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * SIO2Arduino is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SIO2Arduino; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
#include "config.h"
#include "atari.h"
#include "sio_channel.h"
#include "disk_drive.h"
#ifdef LCD_DISPLAY
#include <LiquidCrystal.h>
#endif

/**
 * Function declarations
 */
DriveStatus* getDeviceStatus(int deviceId);
SectorDataInfo* readSector(int deviceId, unsigned long sector, byte *data);
boolean writeSector(int deviceId, unsigned long sector, byte* data, unsigned long length);
boolean format(int deviceId, int density);
int getFileList(int startIndex, int count, FileEntry *entries);
void mountFileIndex(int deviceId, int ix);
void changeDirectory(int ix);

/**
 * Global variables
 */
DriveAccess driveAccess(getDeviceStatus, readSector, writeSector, format);
DriveControl driveControl(getFileList, mountFileIndex, changeDirectory);
SIOChannel sioChannel(PIN_ATARI_CMD, &SIO_UART, &driveAccess, &driveControl);
Sd2Card card;
SdFile currDir;
SdFile file; // TODO: make this unnecessary
DiskDrive drive1;
#ifdef SELECTOR_BUTTON
boolean isSwitchPressed = false;
unsigned long lastSelectionPress;
boolean isFileOpened=false;
#endif
#ifdef RESET_BUTTON
unsigned long lastResetPress;
#endif
#ifdef LCD_DISPLAY
LiquidCrystal lcd(PIN_LCD_RD,PIN_LCD_ENABLE,PIN_LCD_DB4,PIN_LCD_DB5,PIN_LCD_DB6,PIN_LCD_DB7);
#endif

void setup() {
#ifdef DEBUG
  // set up logging serial port
  LOGGING_UART.begin(115200);
#endif

  // initialize serial port to Atari
  SIO_UART.begin(19200);

  // set pin modes
  #ifdef SELECTOR_BUTTON
  pinMode(PIN_SELECTOR, INPUT_PULLUP);
  #endif
  #ifdef RESET_BUTTON
  pinMode(PIN_RESET, INPUT_PULLUP);
  #endif

  #ifdef LCD_DISPLAY
  // set up LCD if appropriate
  lcd.begin(16, 2);
  lcd.print(F("SIO2Arduino"));
  lcd.setCursor(0,1);
  #endif

  // initialize SD card
  LOG_MSG(F("Initializing SD card..."));
  pinMode(PIN_SD_CS, OUTPUT);

  if (!card.begin(PIN_SD_CS, SD_SCK_MHZ(50))) {
    LOG_MSG_CR(F(" failed."));
    #ifdef LCD_DISPLAY
      lcd.print(F("SD Init Error"));
    #endif     
    return;
  }
  
  if (!currDir.open("/")) {
    LOG_MSG_CR(F(" failed."));
    #ifdef LCD_DISPLAY
      lcd.print(F("SD Root Error"));
    #endif     
    return;
  }

  LOG_MSG_CR(F(" done."));
  #ifdef LCD_DISPLAY
    lcd.print(F("READY"));
    delay(3000);
  #endif
  mountFilename(0, "AUTORUN.ATR");
}

void loop() {
  // let the SIO channel do its thing
  sioChannel.runCycle();
  
  #ifdef SELECTOR_BUTTON
  // watch the selector button (accounting for debounce)
  if (digitalRead(PIN_SELECTOR) == LOW && millis() - lastSelectionPress > 250 && isSwitchPressed==false) {
    lastSelectionPress = millis();
    changeDisk(0);
  } else isSwitchPressed=(digitalRead(PIN_SELECTOR) == LOW);
  #endif
  #ifdef RESET_BUTTON
  // watch the reset button
  if (digitalRead(PIN_RESET) == LOW && millis() - lastResetPress > 250) {
    lastResetPress = millis();
    mountFilename(0, "AUTORUN.ATR");
  }
  #endif
  
  #ifdef ARDUINO_TEENSY
    if (SIO_UART.available())
      SIO_CALLBACK();
  #endif
}

void SIO_CALLBACK() {
  // inform the SIO channel that an incoming byte is available
  sioChannel.processIncomingByte();
}

DriveStatus* getDeviceStatus(int deviceId) {
  return drive1.getStatus();
}

SectorDataInfo* readSector(int deviceId, unsigned long sector, byte *data) {
  if (drive1.hasImage()) {
    return drive1.getSectorData(sector, data);
  } else {
    return NULL;
  }
}

boolean writeSector(int deviceId, unsigned long sector, byte* data, unsigned long length) {
  return (drive1.writeSectorData(sector, data, length) == length);
}

boolean format(int deviceId, int density) {
  char name[13];
  
  // get current filename
  file.getName(name, 13);

  // close and delete the current file
  file.close();
  file.remove();

  LOG_MSG(F("Remove old file: "));
  LOG_MSG_CR(name);

  // open new file for writing
  file.open(&currDir, name, O_RDWR | O_SYNC | O_CREAT);

  LOG_MSG(F("Created new file: "));
  LOG_MSG_CR(name);

  // allow the virtual drive to format the image (and possibly alter its size)
  if (drive1.formatImage(&file, density)) {
    // set the new image file for the drive
    drive1.setImageFile(&file);
    return true;
  } else {
    return false;
  }  
}

void changeDisk(int deviceId) {
  dir_t dir;
  char name[13];
  boolean imageChanged = false;

  while (!imageChanged) {
    // get next dir entry
    int8_t result = currDir.readDir((dir_t*)&dir);
    
    // if we got back a 0, rewind the directory and get the first dir entry
    if (!result) {
      currDir.rewind();
      result = currDir.readDir((dir_t*)&dir);
    }
    
    // if we have a valid file response code, open it
    if (result > 0 && isValidFilename((char*)&dir.name)) {
      createFilename(name, (char*)dir.name);
      imageChanged = mountFilename(deviceId, name);
    }
  }
}

boolean isValidFilename(char *s) {
  return (  s[0] != '.' &&    // ignore hidden files 
            s[0] != '_' && (  // ignore bogus files created by OS X
             (s[8] == 'A' && s[9] == 'T' && s[10] == 'R')
          || (s[8] == 'X' && s[9] == 'F' && s[10] == 'D')
#ifdef PRO_IMAGES             
          || (s[8] == 'P' && s[9] == 'R' && s[10] == 'O')
#endif          
#ifdef ATX_IMAGES              
          || (s[8] == 'A' && s[9] == 'T' && s[10] == 'X')
#endif              
#ifdef XEX_IMAGES
          || (s[8] == 'X' && s[9] == 'E' && s[10] == 'X')
#endif              
          )
        );
}

void createFilename(char* filename, char* name) {
  for (int i=0; i < 8; i++) {
    if (name[i] != ' ') {
      *(filename++) = name[i];
    }
  }
  if (name[8] != ' ') {
    *(filename++) = '.';
    *(filename++) = name[8];
    *(filename++) = name[9];
    *(filename++) = name[10];
  }
  *(filename++) = '\0';
}

/**
 * Returns a list of files in the current directory.
 *
 * startIndex = the first valid file in the directory to start from
 * count = how many files to return
 * entries = a pointer to the a FileEntry array to hold the returned data
 */
int getFileList(int startIndex, int count, FileEntry *entries) {
  dir_t dir;
  int currentEntry = 0;

  currDir.rewind();

  int ix = 0;
  while (ix < count) {
    if (currDir.readDir((dir_t*)&dir) < 1) {
      break;
    }
    if (isValidFilename((char*)&dir.name) || (DIR_IS_SUBDIR(&dir) && dir.name[0] != '.')) {
      if (currentEntry >= startIndex) {
        memcpy(entries[ix].name, dir.name, 11);
        if (DIR_IS_SUBDIR(&dir)) {
          entries[ix].isDirectory = true;
        } else {
          entries[ix].isDirectory = false;
        }
        ix++;
      }
      currentEntry++;
    }
  }
  
  return ix;
}

/**
 * Changes the SD card directory.
 *
 * ix = index number (or -1 to go to parent directory)
 */
void changeDirectory(int ix) {
  FileEntry entries[1];
  char name[13];
  SdFile subDir;

  if (ix > -1) {  
    getFileList(ix, 1, entries);
    createFilename(name, entries[0].name);
    if (subDir.open(&currDir, name, O_READ)) {
      currDir = subDir;
    }
  } else {
    if (subDir.open("/")) {
      currDir = subDir;
    }
  }
}

/**
 * Mount a file with the given index number.
 *
 * deviceId = the drive ID
 * ix = the index of the file to mount
 */
void mountFileIndex(int deviceId, int ix) {
  FileEntry entries[1];
  char name[13];

  // figure out what filename is associated with the index
  getFileList(ix, 1, entries);

  // build a full 8.3 filename
  createFilename(name, entries[0].name);

  // mount the image
  mountFilename(deviceId, name);
}

/**
 * Mount a file with the given name.
 *
 * deviceId = the drive ID
 * name = the name of the file to mount
 */
boolean mountFilename(int deviceId, char *name) {
  // close previously open file
  if (file.isOpen()) {
    file.close();
  }
  
  if (file.open(&currDir, name, O_RDWR | O_SYNC) && drive1.setImageFile(&file)) {
    LOG_MSG_CR(name);

    #ifdef LCD_DISPLAY
    lcd.clear();
    lcd.print(name);
    lcd.setCursor(0,1);
    #endif

    return true;
  }
  
  return false;
}


Hello, what a good day, consult and it seems that this one does not give me an error but I want to know if the following compilation is correct and that if there is to define the pins of the display and the sd socket Thank you very much

**Comment by whizzosoftware** [comment]
Glad you got it working. Please see this page for more details on the pin assignments. It should provide the information you need to remap them if you want to.

**Comment by diego76765** [comment]
Hello
