### ISSUE TITLE
Failures trying to compile, IDE 1.8.9

### ISSUE THREAD

**Issue by ethanotoole** [whizzosoftware/SIO2Arduino#9]
Trying to compile SIO2Arduino. I fetched the sdfat library and installed it in the Arduino IDE via the Zip file installer.

At first I hit lots of errors on the includes for sdfatutil.h and sdvolume.h. I grabbed an Adafruit library for SD and installed that, to get past the include failures (Were these retired from sdfat?) but it fails:
Arduino: 1.8.9 (Windows 10), Board: "Arduino/Genuino Uno"
SIO2Arduino:38:25: error: 'getDeviceStatus' was not declared in this scope
 DriveAccess driveAccess(getDeviceStatus, readSector, writeSector, format);

I'm pretty sure the issues all revolve around the library and missing includes.

Any hints?

**Comment by TzOk83** [comment]
Function used in main .ino filed are not declared, you have to declare them all either in the .ino file or in the config.h. Missing declarations are:
`DriveStatus* getDeviceStatus(int deviceId);
SectorDataInfo* readSector(int deviceId, unsigned long sector, byte *data);
boolean writeSector(int deviceId, unsigned long sector, byte* data, unsigned long length);
boolean format(int deviceId, int density);
int getFileList(int startIndex, int count, FileEntry *entries);
void mountFileIndex(int deviceId, int ix);
void changeDirectory(int ix);`

... but there are more errors to solve, yet it is possible to compile and it works (just remember to hit OPTION+RESET, not just RESET to start the .ATR disk).

**Comment by whizzosoftware** [comment]
Updated the code to compile using SdFat 1.1.4.
